### PR TITLE
new skirmish map - caledonia

### PR DESCRIPTION
**Pull request by perfecto25**
new map - caledonia

### CODE REVIEW

**Review by andy5995 — CHANGES_REQUESTED** [review]
@perfecto25 Thanks for the map! Looks great!

A few minor problems: The last release of the community maps mod for the a25 engine was 0.25.15. Only maps compatible with a26 are being accepted now.

The good news is that not much will have to be done to make this map compatible.

This map uses the fancy grass texture, which was removed in a26. 
See https://github.com/0ad-matters/community-maps-2/issues/47 

If you need help with that script, let me know.

In the keywords section of the xml, please change "New" to "community"

>"Keywords": ["community"],

For the map name, please change

"Caledonia" to "Caledonia (2)"

And rename the xml and pmp files to add _2p, for example

Caledonia_2p.xml
Caledonia_2p.pmp

(This repo will gradually be migrating other maps to match the same format of the map names  in the 0ad repo).

It might be easier for you if you wait until you have 0ad a26 available to test the changes with the current release of this mod. That's up to you. Some changes can be made anytime.

**Comment by perfecto25** [comment]
patched for A26, added other required fixes

**Comment by perfecto25** [comment]
also question, is it possible to train roman marian legionaries and gladiators?

Atlas has these units available, but how do I train them in the game?

**Review by andy5995 — CHANGES_REQUESTED** [review]
Thanks for making those changes.

The errors when the map loads will need to be fixed

```
**ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/structures/bridge_wooden.xml"
ERROR: Failed to load entity template 'structures/bridge_wooden'
ERROR: Failed to load entity template 'structures/bridge_wooden'
ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/structures/bridge_wooden.xml"
ERROR: Failed to load entity template 'structures/bridge_wooden'
**
```

Also, please add the map to the README, under the skirmishes section.

**Comment by andy5995** [comment]
> also question, is it possible to train roman marian legionaries and gladiators?
> 
> Atlas has these units available, but how do I train them in the game?

I don't know. Have you tried asking on [the 0ad Reddit](https://www.reddit.com/r/0ad/) or the 0ad forum?

**Comment by andy5995** [comment]
> Thanks for making those changes.
> 
> The errors when the map loads will need to be fixed
> 
> ```
> **ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/structures/bridge_wooden.xml"
> ERROR: Failed to load entity template 'structures/bridge_wooden'
> ERROR: Failed to load entity template 'structures/bridge_wooden'
> ERROR: CCacheLoader failed to find archived or source file for: "simulation/templates/structures/bridge_wooden.xml"
> ERROR: Failed to load entity template 'structures/bridge_wooden'
> **
> ```
> 
> Also, please add the map to the README, under the skirmishes section.

One more thing: On the game setup menu, the civs should be changeable.

**Comment by andy5995** [comment]
> also question, is it possible to train roman marian legionaries and gladiators?
> 
> Atlas has these units available, but how do I train them in the game?

@perfecto25 Looks like this question was answered on reddit

https://www.reddit.com/r/0ad/comments/x7jsm4/comment/iox0ctu/?utm_source=share&utm_medium=web2x&context=3

**Pull request merged**
